spring:
  application:
    name: springboot-rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: /
    publisher-returns: true
server:
  port: 8888

mail:
  to: wangzhifang@duckbillscm.com