spring:
  application:
    name: springboot-rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: sunny
    password: sunny
    publisher-confirms: true
    virtual-host: /
server:
  port: 8888